# Generated by Django 3.2 on 2023-06-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20230602_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='eircode',
            new_name='postcode',
        ),
    ]
