# Generated by Django 3.2 on 2023-05-11 22:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230511_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='https://pc-haven.s3.eu-north-1.amazonaws.com/media/products/noimage.png', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[600, None], upload_to='media/products'),
        ),
    ]
