# Generated by Django 3.2 on 2023-05-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_sub_categeory_product_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
