# Generated by Django 3.2 on 2023-05-12 00:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230511_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='https://pc-haven.s3.eu-north-1.amazonaws.com/media/products/noimage.png', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[600, None], upload_to='products'),
        ),
    ]
