# Generated by Django 3.2 on 2023-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20230519_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygroup',
            name='sub_categories',
            field=models.ManyToManyField(to='products.SubCategory'),
        ),
    ]
