# Generated by Django 3.2 on 2023-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_categorygroup_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.TextField(),
        ),
    ]
