# Generated by Django 3.2 on 2023-05-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20230521_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='information',
            new_name='features',
        ),
    ]
