# Generated by Django 3.2 on 2023-06-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20230615_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=10, help_text='Discount in Percentage', verbose_name='Discount If Product On Sale'),
        ),
    ]
