# Generated by Django 3.2 on 2023-06-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=10, verbose_name='Discount (%) If Product On Sale'),
        ),
    ]
